const KEY='aftWorkoutEntries.v1';
const days={
 day1:{label:'Day 1 — Deadlift + Intervals',focus:'Primary strength day plus introductory running intervals.',ex:[
  ['Trap-bar deadlift','3 × 5','weighted','lb'],['Goblet squat or leg press','3 × 8–10','weighted','lb'],['Dumbbell bench press','3 × 8–10','weighted','lb per hand'],['Seated cable row','3 × 10','weighted','lb'],['Farmer carry','4 × 30–40 yd','carry','lb per hand'],['Plank','3 × 30–60 sec','timed'],['Run / walk intervals','Start: 1 min run + 1 min walk × 10','interval']
 ]},
 day2:{label:'Day 2 — Upper + Easy Cardio',focus:'Upper-body muscular endurance and low-impact aerobic development.',ex:[
  ['Hand-release push-ups','5 submaximal sets','body'],['Lat pulldown or assisted pull-up','3 × 8–12','weighted','lb'],['Dumbbell overhead press','3 × 8–10','weighted','lb per hand'],['Chest-supported row','3 × 10','weighted','lb'],['Walking lunges','3 × 8 each leg','weighted','lb total'],['Dead bug or Pallof press','3 × 10 each side','body'],['Easy cardio','25–35 min conversational effort','cardio']
 ]},
 day3:{label:'Day 3 — Lower Strength + Gym Conditioning',focus:'Build lower-body strength, grip, lateral stability, and repeat-effort conditioning with standard commercial-gym equipment.',ex:[
  ['Goblet squat, front squat, hack squat, or leg press','3 × 6–8','weighted','lb'],['Romanian deadlift','3 × 8','weighted','lb'],['Incline dumbbell press','3 × 8–10','weighted','lb per hand'],['One-arm dumbbell row','3 × 10 each side','weighted','lb'],['Split squat or step-up','3 × 8 each leg','weighted','lb total'],['Side plank','3 × 20–45 sec each side','timed'],['Gym conditioning circuit','3 rounds: reverse lunges, farmer carry or static hold, lateral step-ups, 45–60 sec hard cardio, then 2–3 min rest','circuit']
 ]},
 day4:{label:'Day 4 — Run + Calisthenics',focus:'Build continuous running capacity, then finish with test-relevant calisthenics.',ex:[
  ['Primary run','Follow current run/walk or continuous-run progression','run'],['Hand-release push-ups','4 easy-to-moderate sets','body'],['Plank','3 working sets','timed'],['Air squats','2 × 15','body'],['Mobility','5–10 min','timed']
 ]}
};
let entries=load(),editing=null,installPrompt=null;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const attr=s=>esc(s).replaceAll('\n',' ');
document.addEventListener('DOMContentLoaded',init);
function init(){
 Object.entries(days).forEach(([k,d])=>$('daySelect').insertAdjacentHTML('beforeend',`<option value="${k}">${esc(d.label)}</option>`));
 $('sessionDate').value=today(); setExportDates(); bind(); renderWorkout(); renderHistory(); renderProgress(); updatePreview();
 if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
}
function bind(){
 $('daySelect').onchange=()=>{editing=null;renderWorkout()};
 document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
 $('workoutForm').onsubmit=saveWorkout;$('clearFormButton').onclick=clearForm;$('deleteAllButton').onclick=deleteAll;
 $('copyMarkdownButton').onclick=copyMd;$('downloadMarkdownButton').onclick=()=>download(buildMd(),`aft-training-update-${today()}.md`,'text/markdown');
 $('downloadJsonButton').onclick=exportJson;$('downloadCsvButton').onclick=exportCsv;$('importJsonInput').onchange=importJson;
 $('exportFrom').onchange=updatePreview;$('exportTo').onchange=updatePreview;
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installButton').classList.remove('hidden')});
 $('installButton').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installButton').classList.add('hidden')};
}
function tab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));$(`${name}Tab`).classList.add('active');if(name==='history')renderHistory();if(name==='progress')renderProgress();if(name==='export')updatePreview();scrollTo({top:0,behavior:'smooth'})}
function renderWorkout(saved=null){
 const key=saved?.dayKey||$('daySelect').value||'day1',day=days[key];$('daySelect').value=key;
 const parts=day.label.split('—');$('workoutSummary').innerHTML=`<p class="eyebrow">${esc(parts[0].trim())}</p><h2>${esc(parts.slice(1).join('—').trim())}</h2><p>${esc(day.focus)}</p>`;
 $('exerciseList').innerHTML=day.ex.map((e,i)=>exerciseCard(e,i,saved?.exercises?.[i]||{})).join('');
 document.querySelectorAll('.exercise-complete').forEach(x=>x.onchange=()=>x.closest('.exercise-card').classList.toggle('completed',x.checked));
 $('sessionDate').value=saved?.date||$('sessionDate').value||today();$('duration').value=saved?.duration||'';$('sessionRpe').value=saved?.sessionRpe||'';$('bodyWeight').value=saved?.bodyWeight||'';$('painScore').value=saved?.painScore??'';$('sessionNotes').value=saved?.notes||'';
}
function exerciseCard(e,i,s){const[name,rx,type,unit]=e;return `<section class="card exercise-card ${s.completed?'completed':''}" data-i="${i}"><div class="exercise-heading"><div><h2>${esc(name)}</h2><p>${esc(rx)}</p></div><label class="check-label"><input class="exercise-complete" type="checkbox" ${s.completed?'checked':''}>Done</label></div>${fields(type,unit,s)}<label>Exercise notes<input data-field="notes" value="${attr(s.notes)}" placeholder="Technique, pain, substitutions..."></label></section>`}
function fields(t,u,s){
 if(t==='weighted')return grid(num('load',`Load (${u})`,s.load),num('sets','Sets completed',s.sets),text('reps','Reps by set',s.reps,'5, 5, 5'),num('rpe','Exercise RPE',s.rpe,1,10));
 if(t==='body')return grid(text('reps','Reps by set',s.reps,'10, 9, 8, 8'),num('rpe','Exercise RPE',s.rpe,1,10));
 if(t==='timed')return grid(text('times','Times by set',s.times,'0:45, 0:40, 0:35'),num('rpe','Exercise RPE',s.rpe,1,10));
 if(t==='carry')return grid(num('load',`Load (${u})`,s.load),num('sets','Trips completed',s.sets),num('distance','Distance / trip (yd)',s.distance),num('rpe','Exercise RPE',s.rpe,1,10));
 if(t==='interval')return grid(num('runMinutes','Run interval (min)',s.runMinutes,0,null,.25),num('walkMinutes','Walk interval (min)',s.walkMinutes,0,null,.25),num('rounds','Rounds',s.rounds),num('distance','Total distance (mi)',s.distance,0,null,.01));
 if(t==='cardio')return grid(select('modality','Modality',s.modality,['Incline walk','Bike','Elliptical','Rower','Other']),num('minutes','Minutes',s.minutes),num('distance','Distance',s.distance,0,null,.01),num('avgHr','Average HR',s.avgHr));
 if(t==='circuit')return grid(
  num('rounds','Rounds completed',s.rounds),
  num('lungeLoad','Reverse-lunge load (lb total)',s.lungeLoad),
  num('carryLoad','Carry / hold load per hand (lb)',s.carryLoad),
  num('carrySeconds','Carry / hold duration (sec)',s.carrySeconds),
  num('stepHeight','Step-up height (in)',s.stepHeight),
  select('modality','Hard-cardio modality',s.modality,['Bike','Rower','Elliptical','Treadmill','Other']),
  num('intervalSeconds','Hard interval duration (sec)',s.intervalSeconds),
  text('totalTime','Total circuit time',s.totalTime,'12:30'),
  num('rpe','Circuit RPE',s.rpe,1,10)
);
 if(t==='run')return grid(num('distance','Distance (mi)',s.distance,0,null,.01),text('totalTime','Total time',s.totalTime,'28:45'),num('avgHr','Average HR',s.avgHr),num('maxHr','Max HR',s.maxHr))+`<label>Run structure / splits<input data-field="structure" value="${attr(s.structure)}" placeholder="4 min run / 1 min walk × 6"></label>`;
 return '';
}
const grid=(...x)=>`<div class="form-grid">${x.join('')}</div>`;
function num(f,l,v='',min=0,max=null,step=1){return `<label>${l}<input data-field="${f}" type="number" value="${attr(v)}" ${min!==null?`min="${min}"`:''} ${max!==null?`max="${max}"`:''} step="${step}" inputmode="decimal"></label>`}
function text(f,l,v='',p=''){return `<label>${l}<input data-field="${f}" value="${attr(v)}" placeholder="${attr(p)}"></label>`}
function select(f,l,v='',opts=[]){return `<label>${l}<select data-field="${f}"><option value="">Choose</option>${opts.map(o=>`<option ${v===o?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`}
function saveWorkout(e){e.preventDefault();const key=$('daySelect').value,day=days[key];const exercises=[...document.querySelectorAll('.exercise-card')].map((card,i)=>{const x={name:day.ex[i][0],prescription:day.ex[i][1],type:day.ex[i][2],completed:card.querySelector('.exercise-complete').checked};card.querySelectorAll('[data-field]').forEach(el=>x[el.dataset.field]=el.value.trim());return x});const item={id:editing||id(),date:$('sessionDate').value||today(),dayKey:key,dayLabel:day.label,duration:$('duration').value,sessionRpe:$('sessionRpe').value,bodyWeight:$('bodyWeight').value,painScore:$('painScore').value,notes:$('sessionNotes').value.trim(),exercises,updatedAt:new Date().toISOString()};const i=entries.findIndex(x=>x.id===item.id);i>=0?entries[i]=item:entries.push(item);entries.sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));persist();editing=null;renderWorkout();renderHistory();renderProgress();updatePreview();toast(i>=0?'Workout updated':'Workout saved')}
function clearForm(){editing=null;$('sessionDate').value=today();renderWorkout();toast('Form cleared')}
function renderHistory(){const c=$('historyList');if(!entries.length){c.innerHTML='<div class="empty-state">No workouts saved yet.</div>';return}c.innerHTML=entries.map(e=>{const done=e.exercises.filter(x=>x.completed).slice(0,4).map(x=>`<li>${esc(summary(x))}</li>`).join('');return `<article class="history-item"><div class="history-top"><div><h3>${esc(e.dayLabel)}</h3><p>${dateFmt(e.date)}${e.duration?` · ${esc(e.duration)} min`:''}${e.sessionRpe?` · RPE ${esc(e.sessionRpe)}`:''}</p></div><div class="history-actions"><button class="secondary" onclick="editEntry('${e.id}')">Edit</button><button class="danger" onclick="deleteEntry('${e.id}')">Delete</button></div></div>${done?`<ul class="history-exercises">${done}</ul>`:'<p>No completed exercises marked.</p>'}${e.notes?`<p><strong>Notes:</strong> ${esc(e.notes)}</p>`:''}</article>`}).join('')}
window.editEntry=id=>{const e=entries.find(x=>x.id===id);if(!e)return;editing=id;renderWorkout(e);tab('workout');toast('Editing saved workout')};
window.deleteEntry=id=>{if(!confirm('Delete this workout?'))return;entries=entries.filter(x=>x.id!==id);persist();renderHistory();renderProgress();updatePreview();toast('Workout deleted')};
function deleteAll(){if(!entries.length||!confirm('Delete every saved workout? Export a backup first if needed.'))return;entries=[];persist();renderHistory();renderProgress();updatePreview();toast('All workouts deleted')}
function renderProgress(){const mins=entries.reduce((a,e)=>a+Number(e.duration||0),0),rpes=entries.map(e=>Number(e.sessionRpe)).filter(Boolean),avg=rpes.length?(rpes.reduce((a,b)=>a+b,0)/rpes.length).toFixed(1):'—',wt=entries.find(e=>Number(e.bodyWeight))?.bodyWeight||'—';const cards=[['Sessions',entries.length],['Training time',mins?`${mins} min`:'—'],['Latest weight',wt==='—'?'—':`${wt} lb`],['Avg. session RPE',avg],['Best trap-bar load',bestNum('Trap-bar deadlift','load',' lb')],['Longest logged run',bestNum('Primary run','distance',' mi')],['Best push-up set',bestRep('Hand-release push-ups')],['Longest plank',bestTime('Plank')]];$('progressCards').innerHTML=cards.map(([l,v])=>`<article class="metric"><div class="label">${esc(l)}</div><div class="value">${esc(v||'—')}</div></article>`).join('');const recent=entries.slice(0,8);$('recentProgress').innerHTML=recent.length?recent.map(e=>`<p><strong>${dateFmt(e.date)}</strong> — ${esc(e.dayLabel)}${e.sessionRpe?`, RPE ${esc(e.sessionRpe)}`:''}${e.painScore?`, pain ${esc(e.painScore)}/10`:''}</p>`).join(''):'<div class="empty-state">Progress will appear after the first saved workout.</div>'}
function bestNum(name,f,suf){const a=entries.flatMap(e=>e.exercises).filter(x=>x.name===name).map(x=>Number(x[f])).filter(Number.isFinite);return a.length?`${Math.max(...a)}${suf}`:'—'}
function bestRep(name){const a=entries.flatMap(e=>e.exercises).filter(x=>x.name===name&&x.reps).flatMap(x=>String(x.reps).split(',').map(Number)).filter(Number.isFinite);return a.length?Math.max(...a):'—'}
function bestTime(name){const a=entries.flatMap(e=>e.exercises).filter(x=>x.name===name&&x.times).flatMap(x=>String(x.times).split(',').map(t=>parseTime(t.trim()))).filter(x=>x>0);return a.length?fmtSec(Math.max(...a)):'—'}
function summary(x){const p=[];if(x.load)p.push(`${x.load}${x.type==='carry'?' lb/hand':' lb'}`);if(x.sets)p.push(`${x.sets} sets`);if(x.reps)p.push(`reps ${x.reps}`);if(x.times)p.push(`times ${x.times}`);if(x.runMinutes||x.walkMinutes)p.push(`${x.runMinutes||0} min run / ${x.walkMinutes||0} min walk`);if(x.rounds)p.push(`${x.rounds} rounds`);if(x.distance)p.push(`${x.distance}${['run','interval'].includes(x.type)?' mi':' yd'}`);if(x.minutes)p.push(`${x.minutes} min`);if(x.lungeLoad)p.push(`lunges ${x.lungeLoad} lb total`);if(x.carryLoad)p.push(`carry/hold ${x.carryLoad} lb/hand`);if(x.carrySeconds)p.push(`${x.carrySeconds} sec carry/hold`);if(x.stepHeight)p.push(`${x.stepHeight}-in step`);if(x.modality)p.push(x.modality);if(x.intervalSeconds)p.push(`${x.intervalSeconds} sec hard interval`);if(x.avgHr)p.push(`avg HR ${x.avgHr}`);if(x.maxHr)p.push(`max HR ${x.maxHr}`);if(x.sledLoad)p.push(`legacy sled ${x.sledLoad} lb`);if(x.totalTime)p.push(`time ${x.totalTime}`);if(x.structure)p.push(x.structure);if(x.rpe)p.push(`RPE ${x.rpe}`);return p.join(' · ')||(x.completed?'completed':x.prescription)}
function filtered(){const f=$('exportFrom').value,t=$('exportTo').value;return entries.filter(e=>(!f||e.date>=f)&&(!t||e.date<=t)).sort((a,b)=>a.date.localeCompare(b.date))}
function buildMd(){const a=filtered(),f=$('exportFrom').value,t=$('exportTo').value,mins=a.reduce((s,e)=>s+Number(e.duration||0),0),r=a.map(e=>Number(e.sessionRpe)).filter(Boolean),avg=r.length?(r.reduce((x,y)=>x+y,0)/r.length).toFixed(1):'not recorded';let o=`# AFT Training Update\n\n**Period:** ${f?dateFmt(f):'Beginning'} through ${t?dateFmt(t):'Latest'}  \n**Completed sessions:** ${a.length}  \n**Logged training time:** ${mins?`${mins} minutes`:'not recorded'}  \n**Average session RPE:** ${avg}\n\n`;if(!a.length)return o+'No workouts were logged during this period.\n';o+='## Sessions\n\n';a.forEach(e=>{o+=`### ${dateFmt(e.date)} — ${e.dayLabel}\n`;const m=[];if(e.duration)m.push(`${e.duration} min`);if(e.sessionRpe)m.push(`RPE ${e.sessionRpe}/10`);if(e.bodyWeight)m.push(`${e.bodyWeight} lb`);if(e.painScore!=='')m.push(`pain ${e.painScore}/10`);if(m.length)o+=m.join(' · ')+'\n\n';e.exercises.filter(x=>x.completed||hasData(x)).forEach(x=>o+=`- **${x.name}:** ${summary(x)}\n`);if(e.notes)o+=`\nNotes: ${e.notes}\n`;o+='\n'});return o+'## Coaching request\n\nReview this training block, identify the main strength and conditioning trends, and update my next four-day training block while keeping the November Army fitness goal in mind.\n'}
function updatePreview(){$('markdownPreview').value=buildMd()}
async function copyMd(){const t=buildMd();$('markdownPreview').value=t;try{await navigator.clipboard.writeText(t)}catch{$('markdownPreview').select();document.execCommand('copy')}toast('Chat update copied')}
function exportJson(){download(JSON.stringify({app:'AFT Workout Tracker',version:1,exportedAt:new Date().toISOString(),entries},null,2),`aft-workout-backup-${today()}.json`,'application/json')}
function exportCsv(){const rows=[['date','day','duration_minutes','session_rpe','body_weight_lb','pain_score','exercise','completed','details','exercise_notes','session_notes']];entries.slice().sort((a,b)=>a.date.localeCompare(b.date)).forEach(e=>e.exercises.forEach(x=>rows.push([e.date,e.dayLabel,e.duration,e.sessionRpe,e.bodyWeight,e.painScore,x.name,x.completed?'yes':'no',summary(x),x.notes||'',e.notes||''])));download(rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),`aft-workouts-${today()}.csv`,'text/csv')}
async function importJson(ev){const f=ev.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text()),a=Array.isArray(p)?p:p.entries;if(!Array.isArray(a))throw 0;const clean=a.map(normalizeEntry);if(clean.some(e=>!e))throw 0;if(!confirm(`Import ${clean.length} workouts? Matching IDs will be replaced.`))return;const m=new Map(entries.map(e=>[e.id,e]));clean.forEach(e=>m.set(e.id,e));entries=[...m.values()].sort((a,b)=>b.date.localeCompare(a.date));persist();renderHistory();renderProgress();updatePreview();toast('Backup imported')}catch{alert('That file is not a valid AFT Workout Tracker backup.')}finally{ev.target.value=''}}
function download(content,name,type){const b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function normalizeEntry(e){if(!e||typeof e!=='object'||typeof e.id!=='string'||!e.id||typeof e.date!=='string'||!e.date||!days[e.dayKey])return null;return {...e,dayLabel:typeof e.dayLabel==='string'&&e.dayLabel?e.dayLabel:days[e.dayKey].label,duration:e.duration??'',sessionRpe:e.sessionRpe??'',bodyWeight:e.bodyWeight??'',painScore:e.painScore??'',notes:e.notes??'',updatedAt:typeof e.updatedAt==='string'&&e.updatedAt?e.updatedAt:`${e.date}T12:00:00.000Z`,exercises:Array.isArray(e.exercises)?e.exercises.filter(x=>x&&typeof x==='object'):[]}}
function load(){try{const a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a.map(normalizeEntry).filter(Boolean):[]}catch{return[]}}function persist(){localStorage.setItem(KEY,JSON.stringify(entries))}function hasData(x){return Object.entries(x).some(([k,v])=>!['name','prescription','type','completed'].includes(k)&&v)}
function setExportDates(){const d=new Date(),s=new Date(d);s.setDate(d.getDate()-30);$('exportFrom').value=iso(s);$('exportTo').value=today()}function today(){return iso(new Date())}function iso(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}function dateFmt(s){return new Date(`${s}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}function parseTime(s){const p=s.split(':').map(Number);return p.length===2?p[0]*60+p[1]:Number(s)}function fmtSec(s){return `${Math.floor(s/60)}:${Math.round(s%60).toString().padStart(2,'0')}`}function id(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
let tt;function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('show'),2200)}
